API_ENDPOINT = "https://api.weather.gov"
USER_AGENT = "Home Assistant"
DEFAULT_ICON = "mdi:alert"
DEFAULT_NAME = "NWS Alerts"
CONF_ZONE_ID = "zone_id"
ZONE_ID = ""
VERSION = "1.8.1-S"
DOMAIN = "nws_alerts"
PLATFORM = "sensor"
ATTRIBUTION = "Data provided by Weather.gov"

